# when using environment variables, use this pattern:
# `${${SPRING_PROFILES_ACTIVE}_TECHBD_xyz_abc_def:}`
# - sandbox_TECHBD_xyz_abc_def
# - devl_TECHBD_xyz_abc_def
# - stage_TECHBD_xyz_abc_def
# - prod_TECHBD_xyz_abc_def

logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR
      web: DEBUG
      techbd:
        service:
          http:
            hub:
              prime:
                api: INFO
    ca:
      uhn: WARN
    root: INFO
    io:
      opentelemetry: ERROR
      micrometer: ERROR
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: techbd-hub-prime
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 81bdb4df5dbf13
    password: 8d8fbb25e43ffc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB
      resolve-lazily: true
springdoc:
  api-docs:
    path: /docs/api/openapi
  swagger-ui.path: /docs/api/interactive/index.html
  swagger-ui:
    doc-expansion: none
  show-actuator: true 

server:
  servlet:
    context-path: /
    session:
      cookie:
        secure: true
        http-only: true
        same-site: LAX
      timeout: 60m

org:
  techbd:
    # these should be setup in ENV vars, not here
    # orchestrate:
    #   sftp:
    #     account:
    #       orchctlts:
    #         - tenantId: name1
    #           server: sftp.techbd.org
    #           port: 22
    #           username: name1
    #           password: password
    #         - tenantId: name2
    #           server: sftp.techbd.org
    #           port: 22
    #           username: name2
    #           password: password
    service:
      http:
        hub:
          prime:
            version: @project.version@
            fhirVersion: r4
            igVersion: 1.2.3
            igPackages:
                fhir-v4:
                    # Path to SHIN-NY IG package downloaded from URL: https://shinny.org/us/ny/hrsn/downloads.html
                    shinNy: ig-packages/shin-ny-ig/v${org.techbd.service.http.hub.prime.igVersion}
                    # Path to US Core IG: package downloaded from URL: https://hl7.org/fhir/us/core/STU7/downloads.html
                    usCore: ig-packages/fhir-v4/us-core/stu-7.0.0
                    # Path to SDOH Clinical Care IG package downloaded from URL: https://hl7.org/fhir/us/sdoh-clinicalcare/downloads.html
                    sdoh: ig-packages/fhir-v4/sdoh-clinicalcare/stu-2.2.0
                    # Path to UV-SDC IG package downloaded from URL: https://hl7.org/fhir/uv/sdc/downloads.html
                    uvSdc: ig-packages/fhir-v4/uv-sdc/stu-3.0.0
            defaultSdohFhirProfileUrl: https://shinny.org/us/ny/hrsn/StructureDefinition-SHINNYBundleProfile.json
            defaultDatalakeApiUrl: https://uzrlhp39e0.execute-api.us-east-1.amazonaws.com/dev/HRSNBundle
            operationOutcomeHelpUrl: "https://techbd.org/get-help/"
            fhirUmlsApiKey: umls_api_key
        interactions:
          defaultPersistStrategy: "{ \"nature\": \"fs\" }"
          persist:
            db:
              uri-matcher:
                # TODO: figure out why this is not being read in InteractionsFilter
                regex:
                  - .*
                  - [^/Bundle/.*, POST, persistReqPayload persistRespPayload]         
          saveUserDataToInteractions: true
    udi:
      prime:
        jdbc: 
          # the reason `url` and `jdbcUrl` are both supplied is that some poolers
          # like `url` while others (e.g. Hikari, the default) like `jdbcUrl`
          url: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          jdbcUrl: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          username: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_USERNAME:}
          password: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_PASSWORD:}
          driverClassName: org.postgresql.Driver
          maximumPoolSize: 500 # Set to 500 as per your request
          minimumIdle: 100  # Minimum idle connections in the pool
          idleTimeout: 300000 # 30 seconds to wait for a connection from the pool
          connectionTimeout: 30000  # 5 minutes - idle connections are removed after this time
          maxLifetime: 1800000  # 30 minutes - connections are refreshed after this time
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics: 
      export: 
        url: ${TECHBD_OPEN_OBSERVE_URL}/api/${TECHBD_OPEN_OBSERVE_STREAM_NAME}/v1/metrics
        enabled: true 
        step: 1m # Interval for pushing metrics 
        headers: 
          enabled: true 
          Authorization: Basic ${TECHBD_OPEN_OBSERVE_PASSWORD}
          organization: default
          service: 
            name: default
    tracing: 
      export:
        enabled: true
      endpoint: ${TECHBD_OPEN_OBSERVE_URL}/api/${TECHBD_OPEN_OBSERVE_STREAM_NAME}/v1/traces
      headers: 
        enabled: true  
        Authorization: Basic ${TECHBD_OPEN_OBSERVE_PASSWORD}
        organization: default
        stream-name: ${TECHBD_OPEN_OBSERVE_STREAM_NAME}-traces
        service: 
          name: default